[book]
title = "Electron Microscopy Training"
authors = ["Sangjoon Bob Lee, Guoliang Hu"]
language = "en"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/bobleesj/electron-microscopy"
edit-url-template = "https://github.com/bobleesj/electron-microscopy/edit/main/{path}"
