# Book settings
title: Electron Microscopy Training
author: Sangjoon Bob Lee
logo: ""

# Force all files to be re-built each time
only_build_toc_files: true

# Execution settings
execute:
  execute_notebooks: "off"

# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist

# HTML-specific settings
html:
  use_issues_button: true
  use_repository_button: true
  use_edit_page_button: true
  home_page_in_navbar: false
  extra_footer: ""

# Repository settings
repository:
  url: https://github.com/bobleesj/electron-microscopy
  path_to_book: ""
  branch: main

# Sphinx configuration
sphinx:
  config:
    html_theme: sphinx_book_theme
    html_theme_options:
      pygments_dark_style: monokai
